spring.application.name=backend
# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/proiect}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:parola}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# RabbitMQ retry
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.rabbitmq.template.retry.max-retries=3
spring.rabbitmq.template.retry.multiplier=2

# Nu expune stack trace în răspunsurile HTTP
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false

# JWT
app.jwt.secret=${JWT_SECRET:dGlja2V0LXN5c3RlbS1kZXYtc2VjcmV0LWtleS0yMDI2LWNoYW5nZS1tZS1ub3ch}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# CORS
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}